// Google Apps Script code for Marks Management

export function getAppsScriptCode(webhookUrl, staffEmail, lecturerName) {
  var wh = webhookUrl || 'YOUR_BACKEND_URL/api/marks-sheets/webhook';
  var se = staffEmail || 'staff@example.com';
  var ln = lecturerName || 'Lecturer';

  return [
    '// ============================================',
    '// MIE Faculty Marks - Google Apps Script',
    '// ============================================',
    '',
    'var WEBHOOK_URL = "' + wh + '";',
    'var STAFF_EMAIL = "' + se + '";',
    'var LECTURER_NAME = "' + ln + '";',
    '',
    '// Adds custom menu when sheet opens',
    'function onOpen() {',
    '  SpreadsheetApp.getUi()',
    '    .createMenu("MIE Marks")',
    '    .addItem("Send Selected Columns", "sendSelected")',
    '    .addItem("Create Checkboxes", "createCheckboxes")',
    '    .addItem("Test Email", "testEmail")',
    '    .addToUi();',
    '}',
    '',
    '// Send email for all checked columns',
    'function sendSelected() {',
    '  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();',
    '  var lastCol = sheet.getLastColumn();',
    '  var lastRow = sheet.getLastRow();',
    '',
    '  if (lastCol < 2) {',
    '    SpreadsheetApp.getUi().alert("No test columns found. Add test names in row 1 first.");',
    '    return;',
    '  }',
    '',
    '  // Find which columns are checked',
    '  var selectedColumns = [];',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var testName = sheet.getRange(1, c).getValue();',
    '    var isChecked = sheet.getRange(2, c).getValue();',
    '    if (testName && isChecked === true) {',
    '      var students = [];',
    '      for (var r = 3; r <= lastRow; r++) {',
    '        var name = sheet.getRange(r, 1).getValue();',
    '        var mark = sheet.getRange(r, c).getValue();',
    '        if (name) {',
    '          students.push({ name: name, mark: mark !== "" ? mark : "-" });',
    '        }',
    '      }',
    '      selectedColumns.push({ testName: testName, students: students });',
    '    }',
    '  }',
    '',
    '  if (selectedColumns.length === 0) {',
    '    SpreadsheetApp.getUi().alert("No columns selected. Check the boxes in row 2 for the columns you want to send.");',
    '    return;',
    '  }',
    '',
    '  if (!STAFF_EMAIL || STAFF_EMAIL === "staff@example.com") {',
    '    SpreadsheetApp.getUi().alert("STAFF_EMAIL not set. Edit the script and set your staff email.");',
    '    return;',
    '  }',
    '',
    '  // Build HTML email - vertical table (students = rows, tests = columns)',
    '  var subject = "Marks Update - " + selectedColumns.length + " Test(s) - " + LECTURER_NAME;',
    '',
    '  // Build header row with test names',
    '  var headerCells = "<th style=\\"padding:10px 14px;text-align:left;border:1px solid #e2e8f0;background:#f1f5f9;font-size:12px;color:#475569;font-weight:600;\\">Student</th>";',
    '  for (var i = 0; i < selectedColumns.length; i++) {',
    '    headerCells += "<th style=\\"padding:10px 14px;text-align:center;border:1px solid #e2e8f0;background:#f1f5f9;font-size:12px;color:#475569;font-weight:600;min-width:70px;\\">" + selectedColumns[i].testName + "</th>";',
    '  }',
    '',
    '  // Build data rows - one per student',
    '  var dataRows = "";',
    '  var studentCount = selectedColumns[0].students.length;',
    '  for (var r = 0; r < studentCount; r++) {',
    '    var bg = r % 2 === 0 ? "#ffffff" : "#f8fafc";',
    '    dataRows += "<tr style=\\"background:" + bg + "\\">";',
    '    dataRows += "<td style=\\"padding:10px 14px;border:1px solid #e2e8f0;font-weight:600;color:#1e293b;\\">" + selectedColumns[0].students[r].name + "</td>";',
    '    for (var c = 0; c < selectedColumns.length; c++) {',
    '      var mark = selectedColumns[c].students[r] ? selectedColumns[c].students[r].mark : "-";',
    '      dataRows += "<td style=\\"padding:10px 14px;border:1px solid #e2e8f0;text-align:center;font-weight:500;color:#2563eb;\\">" + mark + "</td>";',
    '    }',
    '    dataRows += "</tr>";',
    '  }',
    '',
    '  // Assemble full HTML',
    '  var html = "<div style=\\"font-family:Segoe UI,Arial,sans-serif;max-width:600px;margin:0 auto;border:1px solid #e2e8f0;border-radius:8px;overflow:hidden;\\">";',
    '  html += "<div style=\\"background:linear-gradient(135deg,#2563eb,#1d4ed8);color:#fff;padding:20px 24px;\\">";',
    '  html += "<h2 style=\\"margin:0;font-size:18px;letter-spacing:-0.3px;\\">Marks Update</h2>";',
    '  html += "<p style=\\"margin:4px 0 0;opacity:0.85;font-size:13px;\\">" + LECTURER_NAME + " &bull; " + new Date().toLocaleDateString() + " &bull; " + selectedColumns.length + " test(s)</p>";',
    '  html += "</div>";',
    '  html += "<table style=\\"width:100%;border-collapse:collapse;\\">";',
    '  html += "<thead><tr>" + headerCells + "</tr></thead>";',
    '  html += "<tbody>" + dataRows + "</tbody>";',
    '  html += "</table>";',
    '  html += "<p style=\\"color:#94a3b8;font-size:11px;margin:0;padding:10px 16px;background:#f8fafc;border-top:1px solid #e2e8f0;\\">MIE Faculty Attendance System &bull; Automated</p>";',
    '  html += "</div>";',
    '',
    '  MailApp.sendEmail({',
    '    to: STAFF_EMAIL,',
    '    subject: subject,',
    '    htmlBody: html',
    '  });',
    '',
    '  // Sync to dashboard',
    '  syncToDashboard(sheet, lastCol);',
    '',
    '  SpreadsheetApp.getUi().alert("Email sent to " + STAFF_EMAIL + " with " + selectedColumns.length + " test column(s)!");',
    '}',
    '',
    'function syncToDashboard(sheet, lastCol) {',
    '  if (!WEBHOOK_URL || WEBHOOK_URL.indexOf("YOUR_BACKEND_URL") !== -1) return;',
    '  var sheetId = sheet.getParent().getId();',
    '  var columns = [];',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var colName = sheet.getRange(1, c).getValue();',
    '    var isApproved = sheet.getRange(2, c).getValue() === true;',
    '    if (colName) {',
    '      columns.push({',
    '        name: colName,',
    '        colIndex: c,',
    '        approved: isApproved,',
    '        approvedAt: isApproved ? new Date().toISOString() : null',
    '      });',
    '    }',
    '  }',
    '  try {',
    '    UrlFetchApp.fetch(WEBHOOK_URL, {',
    '      method: "post",',
    '      contentType: "application/json",',
    '      payload: JSON.stringify({ sheetId: sheetId, columns: columns })',
    '    });',
    '  } catch (err) {',
    '    // silent fail',
    '  }',
    '}',
    '',
    '// Create checkboxes in row 2',
    'function createCheckboxes() {',
    '  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();',
    '  var lastCol = sheet.getLastColumn();',
    '  if (lastCol < 2) {',
    '    SpreadsheetApp.getUi().alert("No test columns found. Add test names in row 1 first.");',
    '    return;',
    '  }',
    '  var checkbox = SpreadsheetApp.newDataValidation().requireCheckbox().build();',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var cell = sheet.getRange(2, c);',
    '    cell.setDataValidation(checkbox);',
    '    cell.setValue(false);',
    '    cell.setHorizontalAlignment("center");',
    '  }',
    '  SpreadsheetApp.getUi().alert("Done! Checkboxes created in row 2 for " + (lastCol - 1) + " test columns.");',
    '}',
    '',
    '// Test email',
    'function testEmail() {',
    '  if (!STAFF_EMAIL || STAFF_EMAIL === "staff@example.com") {',
    '    SpreadsheetApp.getUi().alert("Set STAFF_EMAIL first!");',
    '    return;',
    '  }',
    '  MailApp.sendEmail({',
    '    to: STAFF_EMAIL,',
    '    subject: "Test Email - MIE Faculty System",',
    '    htmlBody: "<div style=\\"font-family:Arial;padding:20px;\\"><h2 style=\\"color:#2563eb;\\">Test Successful!</h2><p>Email is configured correctly for " + LECTURER_NAME + ".</p></div>"',
    '  });',
    '  SpreadsheetApp.getUi().alert("Test email sent to " + STAFF_EMAIL);',
    '}',
  ].join('\n');
}
