// Google Apps Script code for Marks Management
// Returns the script as a plain string (avoids JSX template literal issues)

export function getAppsScriptCode() {
  return [
    '// ============================================',
    '// MIE Faculty Marks - Google Apps Script',
    '// Paste this in your Google Sheet:',
    '// Extensions > Apps Script > Paste > Save',
    '// ============================================',
    '',
    '// Simple trigger - detects checkbox edits',
    '// NOTE: This cannot send emails or call external URLs directly.',
    '// It sets a flag that the installable trigger picks up.',
    'function onEdit(e) {',
    '  if (!e || !e.source) return; // guard against manual run',
    '  var sheet = e.source.getActiveSheet();',
    '  var range = e.range;',
    '  var row = range.getRow();',
    '  var col = range.getColumn();',
    '',
    '  // Row 1 = test names, Row 2 = checkboxes (approval)',
    '  if (row !== 2) return;',
    '  if (range.getValue() !== true) return;',
    '',
    '  // Store the approved column so the installable trigger can process it',
    '  var props = PropertiesService.getScriptProperties();',
    '  props.setProperty("PENDING_COL", col.toString());',
    '  props.setProperty("PENDING_SHEET_ID", e.source.getId());',
    '  props.setProperty("PENDING_TIME", new Date().toISOString());',
    '}',
    '',
    '// Installable trigger - runs when sheet changes',
    '// This CAN send emails and call external URLs',
    'function onSheetChange(e) {',
    '  if (!e || !e.source) return;',
    '  var props = PropertiesService.getScriptProperties();',
    '  var pendingCol = props.getProperty("PENDING_COL");',
    '  if (!pendingCol) return;',
    '',
    '  // Clear the pending flag',
    '  props.deleteProperty("PENDING_COL");',
    '  props.deleteProperty("PENDING_SHEET_ID");',
    '  props.deleteProperty("PENDING_TIME");',
    '',
    '  var sheet = e.source.getActiveSheet();',
    '  var sheetId = e.source.getId();',
    '  var webhookUrl = props.getProperty("WEBHOOK_URL");',
    '',
    '  // Build column status list',
    '  var lastCol = sheet.getLastColumn();',
    '  var columns = [];',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var colName = sheet.getRange(1, c).getValue();',
    '    var isApproved = sheet.getRange(2, c).getValue() === true;',
    '    if (colName) {',
    '      columns.push({',
    '        name: colName,',
    '        colIndex: c,',
    '        approved: isApproved,',
    '        approvedAt: isApproved ? new Date().toISOString() : null',
    '      });',
    '    }',
    '  }',
    '',
    '  // Sync to dashboard',
    '  if (webhookUrl) {',
    '    try {',
    '      UrlFetchApp.fetch(webhookUrl, {',
    '        method: "post",',
    '        contentType: "application/json",',
    '        payload: JSON.stringify({ sheetId: sheetId, columns: columns })',
    '      });',
    '    } catch (err) {',
    '      console.log("Dashboard sync failed: " + err.message);',
    '    }',
    '  }',
    '',
    '  // Check if ALL columns are approved -> send summary email',
    '  var allApproved = columns.length > 0 && columns.every(function(c) { return c.approved; });',
    '  if (allApproved) {',
    '    var staffEmail = props.getProperty("STAFF_EMAIL");',
    '    var lecturerName = props.getProperty("LECTURER_NAME") || "Lecturer";',
    '    if (staffEmail) {',
    '      sendSummaryEmail(staffEmail, lecturerName, sheet);',
    '    }',
    '  }',
    '}',
    '',
    'function sendSummaryEmail(staffEmail, lecturerName, sheet) {',
    '  var lastRow = sheet.getLastRow();',
    '  var lastCol = sheet.getLastColumn();',
    '',
    '  var header = "Student";',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var colName = sheet.getRange(1, c).getValue();',
    '    if (colName) header += " | " + colName;',
    '  }',
    '',
    '  var rows = "";',
    '  for (var r = 3; r <= lastRow; r++) {',
    '    var name = sheet.getRange(r, 1).getValue();',
    '    if (!name) continue;',
    '    var row = name;',
    '    for (var c = 2; c <= lastCol; c++) {',
    '      var mark = sheet.getRange(r, c).getValue();',
    '      row += " | " + (mark !== "" ? mark : "-");',
    '    }',
    '    rows += row + "\\n";',
    '  }',
    '',
    '  var body = "All marks have been approved by " + lecturerName + ".\\n\\n" +',
    '    "Date: " + new Date().toLocaleDateString() + "\\n\\n" +',
    '    header + "\\n" +',
    '    "----------------------------------------\\n" +',
    '    rows + "\\n" +',
    '    "This is an automated email from MIE Faculty Attendance System.";',
    '',
    '  MailApp.sendEmail({',
    '    to: staffEmail,',
    '    subject: "All Marks Approved - " + lecturerName,',
    '    body: body',
    '  });',
    '}',
    '',
    '// Run this ONCE after pasting the script to configure',
    'function setup() {',
    '  var props = PropertiesService.getScriptProperties();',
    '  // IMPORTANT: Edit these values before running!',
    '  props.setProperty("WEBHOOK_URL", "http://localhost:5000/api/marks-sheets/webhook");',
    '  props.setProperty("STAFF_EMAIL", "staff@example.com");',
    '  props.setProperty("LECTURER_NAME", "Your Name");',
    '  Logger.log("Setup complete!");',
    '  Logger.log("IMPORTANT: Go to Triggers (clock icon) and add an onChange trigger for onSheetChange");',
    '}',
    '',
    '// Run this ONCE to create the installable trigger',
    'function createTrigger() {',
    '  var triggers = ScriptApp.getProjectTriggers();',
    '  for (var i = 0; i < triggers.length; i++) {',
    '    if (triggers[i].getHandlerFunction() === "onSheetChange") {',
    '      Logger.log("Trigger already exists!");',
    '      return;',
    '    }',
    '  }',
    '  ScriptApp.newTrigger("onSheetChange")',
    '    .forSpreadsheet(SpreadsheetApp.getActive())',
    '    .onChange()',
    '    .create();',
    '  Logger.log("Installable trigger created successfully!");',
    '}',
  ].join('\n');
}
