// Google Apps Script code for Marks Management

export function getAppsScriptCode(webhookUrl, staffEmail, lecturerName) {
  // Use provided values or defaults
  var wh = webhookUrl || 'YOUR_BACKEND_URL/api/marks-sheets/webhook';
  var se = staffEmail || 'staff@example.com';
  var ln = lecturerName || 'Lecturer';

  return [
    '// ============================================',
    '// MIE Faculty Marks - Google Apps Script',
    '// Paste this in your Google Sheet:',
    '// Extensions > Apps Script > Paste > Save',
    '// ============================================',
    '',
    '// --- CONFIGURATION (edit these!) ---',
    'var WEBHOOK_URL = "' + wh + '";',
    'var STAFF_EMAIL = "' + se + '";',
    'var LECTURER_NAME = "' + ln + '";',
    '',
    '// Simple trigger - detects checkbox edits',
    'function onEdit(e) {',
    '  if (!e || !e.source) return;',
    '  var sheet = e.source.getActiveSheet();',
    '  var range = e.range;',
    '  var row = range.getRow();',
    '  var col = range.getColumn();',
    '',
    '  // Only react to row 2 (checkbox row)',
    '  if (row !== 2) return;',
    '',
    '  // Only react to checkbox being CHECKED (not unchecked)',
    '  if (range.getValue() !== true) return;',
    '',
    '  // Store pending change for installable trigger',
    '  var props = PropertiesService.getScriptProperties();',
    '  props.setProperty("PENDING_COL", col.toString());',
    '  props.setProperty("PENDING_TIME", new Date().toISOString());',
    '}',
    '',
    '// Installable trigger - handles sync + email',
    '// (Run createTrigger() once to set this up)',
    'function onSheetChange(e) {',
    '  if (!e || !e.source) return;',
    '  var props = PropertiesService.getScriptProperties();',
    '  var pendingCol = props.getProperty("PENDING_COL");',
    '  if (!pendingCol) return;',
    '',
    '  props.deleteProperty("PENDING_COL");',
    '  props.deleteProperty("PENDING_TIME");',
    '',
    '  var sheet = e.source.getActiveSheet();',
    '  var sheetId = e.source.getId();',
    '',
    '  // Build column status',
    '  var lastCol = sheet.getLastColumn();',
    '  var columns = [];',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var colName = sheet.getRange(1, c).getValue();',
    '    var hasCheckbox = sheet.getRange(2, c).isChecked();',
    '    if (colName) {',
    '      columns.push({',
    '        name: colName,',
    '        colIndex: c,',
    '        approved: hasCheckbox === true,',
    '        approvedAt: hasCheckbox === true ? new Date().toISOString() : null',
    '      });',
    '    }',
    '  }',
    '',
    '  // Sync to dashboard',
    '  if (WEBHOOK_URL && WEBHOOK_URL.indexOf("YOUR_BACKEND_URL") === -1) {',
    '    try {',
    '      UrlFetchApp.fetch(WEBHOOK_URL, {',
    '        method: "post",',
    '        contentType: "application/json",',
    '        payload: JSON.stringify({ sheetId: sheetId, columns: columns })',
    '      });',
    '    } catch (err) {',
    '      console.log("Dashboard sync failed: " + err.message);',
    '    }',
    '  }',
    '',
    '  // All approved? Send summary email',
    '  var allApproved = columns.length > 0 && columns.every(function(c) { return c.approved; });',
    '  if (allApproved) {',
    '    sendSummaryEmail(STAFF_EMAIL, LECTURER_NAME, sheet);',
    '  }',
    '}',
    '',
    'function sendSummaryEmail(staffEmail, lecturerName, sheet) {',
    '  var lastRow = sheet.getLastRow();',
    '  var lastCol = sheet.getLastColumn();',
    '',
    '  var header = "Student";',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var colName = sheet.getRange(1, c).getValue();',
    '    if (colName) header += " | " + colName;',
    '  }',
    '',
    '  var rows = "";',
    '  for (var r = 3; r <= lastRow; r++) {',
    '    var name = sheet.getRange(r, 1).getValue();',
    '    if (!name) continue;',
    '    var rowStr = name;',
    '    for (var c = 2; c <= lastCol; c++) {',
    '      var mark = sheet.getRange(r, c).getValue();',
    '      rowStr += " | " + (mark !== "" ? mark : "-");',
    '    }',
    '    rows += rowStr + "\\n";',
    '  }',
    '',
    '  var body = "All marks have been approved by " + lecturerName + ".\\n\\n" +',
    '    "Date: " + new Date().toLocaleDateString() + "\\n\\n" +',
    '    header + "\\n" +',
    '    "----------------------------------------\\n" +',
    '    rows + "\\n" +',
    '    "This is an automated email from MIE Faculty Attendance System.";',
    '',
    '  MailApp.sendEmail({',
    '    to: staffEmail,',
    '    subject: "All Marks Approved - " + lecturerName,',
    '    body: body',
    '  });',
    '}',
    '',
    '// ============================================',
    '// SETUP FUNCTIONS - Run these once manually',
    '// ============================================',
    '',
    '// Step 1: Run this to create checkboxes in row 2',
    'function createCheckboxes() {',
    '  var sheet = SpreadsheetApp.getActiveSpreadsheet().getActiveSheet();',
    '  var lastCol = sheet.getLastColumn();',
    '  if (lastCol < 2) {',
    '    Logger.log("No test columns found. Add test names in row 1 first.");',
    '    return;',
    '  }',
    '  for (var c = 2; c <= lastCol; c++) {',
    '    var cell = sheet.getRange(2, c);',
    '    if (!cell.isChecked && !cell.getValue()) {',
    '      cell.insertCheckboxes();',
    '    }',
    '  }',
    '  Logger.log("Checkboxes created in row 2 for " + (lastCol - 1) + " test columns!");',
    '}',
    '',
    '// Step 2: Run this to create the installable trigger',
    'function createTrigger() {',
    '  var triggers = ScriptApp.getProjectTriggers();',
    '  for (var i = 0; i < triggers.length; i++) {',
    '    if (triggers[i].getHandlerFunction() === "onSheetChange") {',
    '      Logger.log("Trigger already exists!");',
    '      return;',
    '    }',
    '  }',
    '  ScriptApp.newTrigger("onSheetChange")',
    '    .forSpreadsheet(SpreadsheetApp.getActive())',
    '    .onChange()',
    '    .create();',
    '  Logger.log("Installable trigger created! Emails will now be sent when all columns are approved.");',
    '}',
    '',
    '// Step 3 (optional): Run this to remove all triggers',
    'function removeTriggers() {',
    '  var triggers = ScriptApp.getProjectTriggers();',
    '  for (var i = 0; i < triggers.length; i++) {',
    '    if (triggers[i].getHandlerFunction() === "onSheetChange") {',
    '      ScriptApp.deleteTrigger(triggers[i]);',
    '    }',
    '  }',
    '  Logger.log("Triggers removed.");',
    '}',
  ].join('\n');
}
